pyhton exception  handling will be performed here
